spring:
  application:
    name: asset-service
  cloud:
    azure:
      storage:
        queue:
          enabled: false
        fileshare:
          enabled: false
        blob:
          enabled: true
          # This is hardcoded to use Azurite, we should do something smarter if we want to dynamically change with Azure
          account-name: devstoreaccount1
          account-key: Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
          endpoint: ${AZURE_HOST}:10000/devstoreaccount1
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: [ health ]
springdoc:
  swagger-ui:
    enabled: true
    path: "/swagger-ui"
  api-docs:
    enabled: true
    path: "/docs"
