name: 'Compute Image Name for Env'
description: 'Computes the final image name based on the environment'
inputs:
  base-image-name:
    description: 'Base image name'
    required: true
  main-branch-name:
    description: "Main branch of repository"
    required: false
    default: "master"
outputs:
  image_name:
    description: "Final image name"
    value: ${{ steps.image-env-name.outputs.image_name }}
runs:
  using: "composite"
  steps:
    - name: Setup Image Name for Env
      id: image-env-name
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/${{ inputs.main-branch-name }}' ]]; then
          echo "image_name=${{ inputs.base-image-name }}" >> $GITHUB_OUTPUT
        elif [[ ${{ github.ref }} == 'refs/heads/test/'* ]]; then
          echo "image_name=${{ inputs.base-image-name }}-dev" >> $GITHUB_OUTPUT
        else
          echo "::error::Unsupported branch name"
          exit 1
        fi
      shell: bash