name: 'Compute Image Tag for Branch and Env'
description: 'Compute Image Tag for Branch and Env'
outputs:
  tag:
    description: "Tag"
    value: ${{ steps.tag-branch-name.outputs.tag }}
runs:
  using: "composite"
  steps:
    - name: Setup Branch Name for Tag
      id: tag-branch-name
      run: |
        RESULT=$(echo "${{github.ref_name}}.${{github.run_number}}" | tr / -)
        echo "tag=$RESULT" >> $GITHUB_OUTPUT
      shell: bash